parameters:
  dol_ldap.domains.parameters:
  zend.ldap_driver.class: Zend\Ldap\Ldap
  dol_ldap.ldap_driver.multiple.class: DoL\LdapBundle\Driver\MultipleLdapDriver
  dol_ldap.ldap_driver.zend.class: DoL\LdapBundle\Driver\ZendLdapDriver

services:
  # Zend Ldap driver
  dol_ldap.ldap_driver.zend.driver:
    class: "%zend.ldap_driver.class%"
    public: false

  # DoL Zend Ldap driver
  dol_ldap.ldap_driver.zend:
    class: "%dol_ldap.ldap_driver.zend.class%"
    arguments: [ "@dol_ldap.ldap_driver.zend.driver", "@logger" ]
    tags:
      - { name: monolog.logger, channel: ldap_driver }
